name: Docker Compose Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Run tests in container
        run: docker-compose exec -T web python manage.py test

      - name: Show logs if tests failed
        if: failure()
        run: docker-compose logs

      - name: Stop services
        if: always()
        run: docker-compose down