name: Docker Compose Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Show running containers
        run: docker ps -a

      - name: Show web service logs if failed
        if: failure()
        run: docker-compose logs web

      - name: Run tests
        run: docker-compose exec -T web python manage.py test courses --keepdb